export const COMPANY_REGISTRATION_REQ = "COMPANY_REGISTRATION_REQ";
export const COMPANY_REGISTRATION_SUCCESS = "COMPANY_REGISTRATION_SUCCESS";
export const COMPANY_REGISTRATION_FAIL = "COMPANY_REGISTRATION_FAIL";
export const COMPANY_REGISTRATION_RESET = "COMPANY_REGISTRATION_RESET";

export const COMPANY_LOGIN_REQ = "COMPANY_LOGIN_REQ";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS";
export const COMPANY_LOGIN_FAIL = "COMPANY_LOGIN_FAIL";
export const COMPANY_LOGOUT = "COMPANY_LOGOUT";

export const COMPANY_UPDATE_REQ = "COMPANY_UPDATE_REQ";
export const COMPANY_UPDATE_SUCCESS = "COMPANY_UPDATE_SUCCESS";
export const COMPANY_UPDATE_FAIL = "COMPANY_UPDATE_FAIL";
export const COMPANY_UPDATE_RESET = "COMPANY_UPDATE_RESET";

export const COMPANY_REMOVE_REQ = "COMPANY_REMOVE_REQ";
export const COMPANY_REMOVE_SUCCESS = "COMPANY_REMOVE_SUCCESS";
export const COMPANY_REMOVE_FAIL = "COMPANY_REMOVE_FAIL";
export const COMPANY_REMOVE_RESET = "COMPANY_REMOVE_RESET";

export const COMPANY_POST_JOB_REQ = "COMPANY_POST_JOB_REQ";
export const COMPANY_POST_JOB_SUCCESS = "COMPANY_POST_JOB_SUCCESS";
export const COMPANY_POST_JOB_FAIL = "COMPANY_POST_JOB_FAIL";
export const COMPANY_POST_JOB_RESET = "COMPANY_POST_JOB_RESET";

export const COMPANY_GET_JOBS_REQ = "COMPANY_GET_JOBS_REQ";
export const COMPANY_GET_JOBS_SUCCESS = "COMPANY_GET_JOBS_SUCCESS";
export const COMPANY_GET_JOBS_FAIL = "COMPANY_GET_JOBS_FAIL";
export const COMPANY_GET_JOBS_RESET = "COMPANY_GET_JOBS_RESET";

export const COMPANY_GET_APPLICANTS_REQ = "COMPANY_GET_APPLICANTS_REQ";
export const COMPANY_GET_APPLICANTS_SUCCESS = "COMPANY_GET_APPLICANTS_SUCCESS";
export const COMPANY_GET_APPLICANTS_FAIL = "COMPANY_GET_APPLICANTS_FAIL";
export const COMPANY_GET_APPLICANTS_RESET = "COMPANY_GET_APPLICANTS_RESET";

export const COMPANY_APPLICANTION_STATUS_REQ = "COMPANY_APPLICANTION_STATUS_REQ";
export const COMPANY_APPLICANTION_STATUS_SUCCESS = "COMPANY_APPLICANTION_STATUS_SUCCESS";
export const COMPANY_APPLICANTION_STATUS_FAIL = "COMPANY_APPLICANTION_STATUS_FAIL";
export const COMPANY_APPLICANTION_STATUS_RESET = "COMPANY_APPLICANTION_STATUS_RESET";

export const COMPANY_JOB_VISIBILITY_REQ = "COMPANY_JOB_VISIBILITY_REQ";
export const COMPANY_JOB_VISIBILITY_SUCCESS = "COMPANY_JOB_VISIBILITY_SUCCESS";
export const COMPANY_JOB_VISIBILITY_FAIL = "COMPANY_JOB_VISIBILITY_FAIL";
export const COMPANY_JOB_VISIBILITY_RESET = "COMPANY_JOB_VISIBILITY_RESET";